services:
  kaboom:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - peerserver

  peerserver:
    image: peerjs/peerjs-server
    ports:
      - "3090:9000"
    command: --port 9000 --path /peerjs --key peerjs
