services:
  kaboom:
    build:
      context: .
      args:
        - VITE_PEER_HOST=192.168.5.22
        - VITE_PEER_PORT=3090
        - VITE_PEERJS_ID=kaboom123
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - peerserver

  peerserver:
    image: peerjs/peerjs-server
    ports:
      - "3090:9000"
    command: --port 9000 --path /peerjs --key peerjs --allow_discovery --cors http://192.168.5.22:3000
